runtime: nodejs20
instance_class: F2
env: standard
automatic_scaling:
  max_instances: 20
vpc_access_connector:
  name: projects/YOUR_PROJECT_ID/locations/YOUR_REGION/connectors/YOUR_CONNECTOR_NAME
  egress_setting: all-traffic